### ISSUE TITLE
for lable

### ISSUE THREAD

**Issue by Moira2332** [Moira2332/confectionery-website#1]
<img width="496" alt="screen shot 2016-12-14 at 11 55 44 am" src="https://cloud.githubusercontent.com/assets/16653517/21191815/5e14ca60-c1f4-11e6-8873-8d5669dc2216.png">
 not sure how to fix this

**Comment by Moira2332** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
The `id` appears to be missing from the message `<textarea>`

**Comment by Moira2332** [comment]
oh, thank you haha! Can you give any tips on how to make my performance better I've done everything from the videos? @thomasjbradley

**Comment by thomasjbradley** [comment]
You better talk to @melissaroy about it.

**Comment by Moira2332** [comment]
Okay thank you for your help!
